// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddproducttocartController from "./addproducttocart_controller"
application.register("addproducttocart", AddproducttocartController)

import AutocompleteproductController from "./autocompleteproduct_controller"
application.register("autocompleteproduct", AutocompleteproductController)

import CarouselHomepageController from "./carousel_homepage_controller"
application.register("carousel-homepage", CarouselHomepageController)

import CategoryController from "./category_controller"
application.register("category", CategoryController)

import DashboardController from "./dashboard_controller"
application.register("dashboard", DashboardController)

import DebounceController from "./debounce_controller"
application.register("debounce", DebounceController)

import DisplayCartController from "./display_cart_controller"
application.register("display-cart", DisplayCartController)

import FavoritesController from "./favorites_controller"
application.register("favorites", FavoritesController)

import GallerieController from "./gallerie_controller"
application.register("gallerie", GallerieController)

import LineItemQuantityController from "./line_item_quantity_controller"
application.register("line-item-quantity", LineItemQuantityController)

import LoadvariantsController from "./loadvariants_controller"
application.register("loadvariants", LoadvariantsController)

import MapController from "./map_controller"
application.register("map", MapController)

import PreviewPriceChangeController from "./preview_price_change_controller"
application.register("preview-price-change", PreviewPriceChangeController)

import SearchController from "./search_controller"
application.register("search", SearchController)

import ShareController from "./share_controller"
application.register("share", ShareController)
