// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CategoryController from "./category_controller"
application.register("category", CategoryController)

import DebounceController from "./debounce_controller"
application.register("debounce", DebounceController)

import FavoritesController from "./favorites_controller"
application.register("favorites", FavoritesController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LineItemQuantityController from "./line_item_quantity_controller"
application.register("line-item-quantity", LineItemQuantityController)

import MapController from "./map_controller"
application.register("map", MapController)

import DisplayCartController from "./display_cart_controller"
application.register("display-cart", DisplayCartController)

import PreviewPriceChangeController from "./preview_price_change_controller"
application.register("preview-price-change", PreviewPriceChangeController)

import ScrollController from "./scroll_controller"
application.register("scroll", ScrollController)

import SearchController from "./search_controller"
application.register("search", SearchController)

import SearchareaController from "./searcharea_controller"
application.register("searcharea", SearchareaController)

import DashboardController from "./dashboard_controller"
application.register("dashboard", DashboardController)

import ShareController from "./share_controller"
application.register("share", ShareController)

import GallerieController from "./gallerie_controller"
application.register("gallerie", GallerieController)


